server:
  port: 8081

spring:
  application:
    name: user-service

  # Настройки базы данных (PostgreSQL)
  datasource:
    url: jdbc:postgresql://62.213.14.255:5437/user_service_db
    username: postgres
    password: postgres

  # Настройки JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Настройки Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # Сериализация: ключ — строка, значение — JSON
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            # Добавление информации о типах в заголовки (нужно для Consumer)
            add:
              type:
                headers: true
    consumer:
      properties:
        spring:
          deserializer:
            value:
              # Делегат для ErrorHandlingDeserializer
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/ # Адрес сервера Discovery
      register-with-eureka: true
      fetch-registry: true

# Настройка логирования
logging:
  level:
    org:
      springframework:
        kafka: DEBUG

test.message: "Newыыы"
